// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/Feed.tsx": () => import("../components/mockups/dashboard/Feed.tsx"),
  "./components/mockups/dashboard/FeedDefault.tsx": () => import("../components/mockups/dashboard/FeedDefault.tsx"),
  "./components/mockups/dashboard/FeedSearch.tsx": () => import("../components/mockups/dashboard/FeedSearch.tsx"),
  "./components/mockups/dashboard/Profile.tsx": () => import("../components/mockups/dashboard/Profile.tsx"),
  "./components/mockups/dashboard/Review.tsx": () => import("../components/mockups/dashboard/Review.tsx"),
  "./components/mockups/landing/App.tsx": () => import("../components/mockups/landing/App.tsx"),
  "./components/mockups/mobile/MobileFeed.tsx": () => import("../components/mockups/mobile/MobileFeed.tsx"),
  "./components/mockups/mobile/MobileProfile.tsx": () => import("../components/mockups/mobile/MobileProfile.tsx"),
  "./components/mockups/mobile/MobileReel.tsx": () => import("../components/mockups/mobile/MobileReel.tsx"),
  "./components/mockups/mobile/MobileReview.tsx": () => import("../components/mockups/mobile/MobileReview.tsx")
};
