// This file is auto-generated by previewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/screens/dashboard/Feed.tsx": () => import("../components/screens/dashboard/Feed.tsx"),
  "./components/screens/dashboard/FeedDefault.tsx": () => import("../components/screens/dashboard/FeedDefault.tsx"),
  "./components/screens/dashboard/FeedSearch.tsx": () => import("../components/screens/dashboard/FeedSearch.tsx"),
  "./components/screens/dashboard/Profile.tsx": () => import("../components/screens/dashboard/Profile.tsx"),
  "./components/screens/dashboard/Review.tsx": () => import("../components/screens/dashboard/Review.tsx"),
  "./components/screens/landing/App.tsx": () => import("../components/screens/landing/App.tsx"),
  "./components/screens/mobile/MobileFeed.tsx": () => import("../components/screens/mobile/MobileFeed.tsx"),
  "./components/screens/mobile/MobileProfile.tsx": () => import("../components/screens/mobile/MobileProfile.tsx"),
  "./components/screens/mobile/MobileReel.tsx": () => import("../components/screens/mobile/MobileReel.tsx"),
  "./components/screens/mobile/MobileReview.tsx": () => import("../components/screens/mobile/MobileReview.tsx")
};
